### ISSUE TITLE
Needs an update

### ISSUE THREAD

**Issue by SHOTbyGUN** [looterz/wargame-rcon#1]
Tried installing with npm
   - npm repository was expired

Tried installing with git clone
  - didin't work until I ran npm update

Added chmod +x for bin/wargame-rcon and tried to use it
  - crashes quite easy
  - /connect just returns symbols + does server does not register rcon attempt

But since this is the only rcon client what is supposed to work on Linux, it would be great if you could update it :)

**Comment by looterz** [comment]
This project is no longer maintained, and has some annoying bugs. It's best if you use one of the alternative tools on the Red Dragon subforum for dedicated servers.
